Bug/pn 8576
pagopa/pn-radd-fsu pull request #61
Opened 2023-10-26 13:16 UTC by CriMDev97

2023-10-26 15:40 UTC, vincenzo-racca-pa requested changes

2023-10-26 15:40 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/radd/middleware/db/impl/RaddTransactionDAOImpl.java
> +                .then(Mono.fromCallable(() -> {
possiamo evitare di fare questo e passare lo stato come un parametro del metodo updateStatus? (così l'updateStatus modifica lo stato e fa update su DB )

2023-10-27 07:47 UTC, CriMDev97 commented on src/main/java/it/pagopa/pn/radd/middleware/db/impl/RaddTransactionDAOImpl.java
> +                .then(Mono.fromCallable(() -> {
Si va bene, procediamo con la modifica

2023-10-27 15:31 UTC, vincenzo-racca-pa approved these changes

2023-10-27 15:52 UTC, merged